### ISSUE TITLE
zbxtable-web登录提示Unexpected token

### ISSUE THREAD

**Issue by johnies-sun** [canghai908/zbxtable-web#1]
安装和启动均无报错，在登录页面输入用户密码提示

Unexpected token < in JSON at position 0

**Comment by canghai908** [comment]
先查看配置文件里zabbix server api地址是否正确，是否可以web访问。其次ps -ef查看zbxtable进程是否存在。具体错误可查看日志文件。

**Comment by johnies-sun** [comment]
已确认是DB用户没有DDL权限导致。

**Comment by canghai908** [comment]
好的

**Comment by brucetasy** [comment]
在 ZbxTable Web 畫面 輸入正確的帳號與密碼 和 錯誤的帳號與密碼，都沒有回應 畫面一直在轉圈圈。
跟 展示的URL  https://demo.zbxtable.com/ 是一樣的狀態 。
可以請問哪裡設定錯誤嗎 ?

**Comment by canghai908** [comment]
转圈是后端挂了，检查zbxtable后端日志，以及zbxtable服务是否启动。Demo网站已修复。
